build: off

install:
    - cmd: choco upgrade chocolatey
    - cmd: choco install naps2
    - cmd: SET PATH=%PATH%;C:\Program Files (x86)\NAPS2
    - cmd: NAPS2.Console.exe --install generic-import
    - cmd: NAPS2.Console.exe --install ocr-eng
    - cmd: NAPS2.Console.exe --install ocr-deu

test_script:
    - cmd: curl -fsS -o epson17853.exe https://ftp.epson.com/drivers/epson17853.exe
    - cmd: curl -fsS -o EEM_31153.exe https://ftp.epson.com/drivers/EEM_31153.exe
    - cmd: cscript scan.vbs

after_test:
    - cmd: 7z a epsoscanify.zip %APPVEYOR_BUILD_FOLDER%\scan.vbs %APPVEYOR_BUILD_FOLDER%\*.exe

artifacts:
    - path: epsoscanify.zip
      name: epsoscanify

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

    # Deploy to GitHub Releases
    - provider: GitHub
      artifact: epsoscanify.zip           # upload all NuGet packages to release assets
      draft: false
      prerelease: false
      on:
        branch: master                # release from master branch only
        APPVEYOR_REPO_TAG: true       # deploy on tag push only


# deploy:
#   release: myproduct-v$(APPVEYOR_BUILD_VERSION)
#   description: 'Release description'
#   provider: GitHub
#   auth_token:
#     secure: <your encrypted token> # your encrypted token from GitHub
#   artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                 # release from master branch only
#     APPVEYOR_REPO_TAG: true        # deploy on tag push only