#skip_tags: true

build: off

install:
    - cmd: choco upgrade chocolatey
    - cmd: choco install naps2
    - cmd: SET PATH=%PATH%;C:\Program Files (x86)\NAPS2
    - cmd: NAPS2.Console.exe --install generic-import
    - cmd: NAPS2.Console.exe --install ocr-eng
    - cmd: NAPS2.Console.exe --install ocr-deu

test_script:
    # Download Recovery Mode Firmware CS01I6
    - cmd: curl -fsS -o FW_CS01I6.exe https://ftp.epson.com/drivers/FW_CS01I6.exe
    # Download Scanner Driver and EPSON Scan Utility v3.7.7.1
    - cmd: curl -fsS -o epson17853.exe https://ftp.epson.com/drivers/epson17853.exe
    # Download Epson Event Manager v3.11.53
    - cmd: curl -fsS -o EEM_31153.exe https://ftp.epson.com/drivers/EEM_31153.exe
    - cmd: cscript scan.vbs

after_test:
    - cmd: 7z a epsoscanify-$(APPVEYOR_REPO_TAG_NAME).zip %APPVEYOR_BUILD_FOLDER%\scan.vbs %APPVEYOR_BUILD_FOLDER%\*.exe

artifacts:
    - path: epsoscanify-$(APPVEYOR_REPO_TAG_NAME).zip
      name: epsoscanify

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

    # Deploy to GitHub Releases
    - tag: $(APPVEYOR_REPO_TAG_NAME)
      release: epsoscanify-$(APPVEYOR_REPO_TAG_NAME)
      description: 'Release description'
      provider: GitHub
      auth_token:
          secure: BS0OnZTLOLnMhVaRVoIKtU5knp/cPdgY4ADI3SGLhyjyYLoIUU+pthc+tK2yTRad
      artifact: epsoscanify.zip
      draft: false
      prerelease: false
      on:
          branch: master                # release from master branch only
          APPVEYOR_REPO_TAG: true       # deploy on tag push only
