build: off

install:
    - cmd: choco install naps2
    - cmd: C:\Program Files (x86)\NAPS2\NAPS2.Console.exe --install generic-import
    - cmd: C:\Program Files (x86)\NAPS2\NAPS2.Console.exe --install ocr-eng
    - cmd: C:\Program Files (x86)\NAPS2\NAPS2.Console.exe --install ocr-deu

test_script:
    - cmd: curl -fsS -o epson17853.exe https://ftp.epson.com/drivers/epson17853.exe
    - cmd: curl -fsS -o EEM_31153.exe https://ftp.epson.com/drivers/EEM_31153.exe
    - cmd: NAPS2.Console.exe --help
    - cmd: cscript scan.vbs