build: off

install:
    - cmd: choco install naps2
    - cmd: SET PATH=%PATH%;C:\Program Files (x86)\NAPS2
    - cmd: NAPS2.Console.exe --install generic-import
    - cmd: NAPS2.Console.exe --install ocr-eng
    - cmd: NAPS2.Console.exe --install ocr-deu

test_script:
    - cmd: wget https://ftp.epson.com/drivers/epson17853.exe
    - cmd: wget https://ftp.epson.com/drivers/EEM_31153.exe
    - cmd: NAPS2.Console.exe --help
    - cmd: cscript scan.vbs